### ISSUE TITLE
Manual save only

### ISSUE THREAD

**Issue by masaki39** [antoniotejada/obsidian-edit-history#12] opened 2024-02-26 14:47 UTC
Thank you for the wonderful plugin.
I appreciate that it saves automatically, but I only want to save versions of specific files.
Can you make it possible to turn off automatic saving?

**Comment by antoniotejada** [comment] 2024-02-26 23:14
Duplicate of #1, closing.

**Closed by antoniotejada** 2024-02-26 23:14 UTC

**Comment by antoniotejada** [comment] 2024-02-27 00:13
You call it "turn off autosave" but from your description

> I only want to save versions of specific files.

what you really want is a whitelist, which is what #1 explains how to do.

**Comment by masaki39** [comment] 2024-02-27 00:26
What I wanted to do was to save specific files and save manually only. (Because there is a command to save manually)
Thanks to #1, I was able to achieve saving only specific files.

**Comment by antoniotejada** [comment] 2024-02-27 00:47
Setting "Minimum seconds between edits" to 0 should disable autosaving.

See
https://github.com/antoniotejada/obsidian-edit-history/blob/b7634fef3a2fe28486b8c0682a638a71eb294713/main.ts#L191

**Comment by masaki39** [comment] 2024-02-27 00:56
Oh, thank you for your responding.

**Comment by antoniotejada** [comment] 2024-02-27 01:12
No problem, I've modified the settings description to clarify that, will
get updated whenever I push a new version (not planned yet).
